# Data Truth & Joining Datasets
### Stephen Alger 
### March 5 2021
---
### Visualisation Objective: Irish General Election Results 2016
> Data Source(s): <br>
> https://data.gov.ie/dataset/candidate-details-for-general-election-2016 <br>
> https://data.gov.ie/dataset/general-election-2016-constituency-details <br>
> https://data.gov.ie/dataset/general-election-2016-count-details <br>
---

In [11]:
#Dependency Installation & Loading
install.packages("sqldf")
install.packages("cowplot")
install.packages("viridis")
install.packages("tidyverse")

library(viridis)
library(tidyverse)
library(cowplot)
library(sqldf)

#Set Environment Plot Size:
options(repr.plot.width=25, repr.plot.height=10)

#Define my Own Theme                           
my_Theme <- theme(plot.title = element_text(face="bold",size=40),
                  plot.subtitle = element_text(face="italic", size = 20),
                  axis.title = element_text(face="bold",size=20),
                  axis.text = element_text(size=20),
                  plot.caption = element_text(size = 16),
                  legend.title = element_text(size = 16),
                  legend.text  = element_text(size = 14))

The downloaded binary packages are in
	/var/folders/tj/n0crv2hj7zj5vxqbn5kjllf80000gn/T//Rtmp7WHzWS/downloaded_packages

The downloaded binary packages are in
	/var/folders/tj/n0crv2hj7zj5vxqbn5kjllf80000gn/T//Rtmp7WHzWS/downloaded_packages

The downloaded binary packages are in
	/var/folders/tj/n0crv2hj7zj5vxqbn5kjllf80000gn/T//Rtmp7WHzWS/downloaded_packages

The downloaded binary packages are in
	/var/folders/tj/n0crv2hj7zj5vxqbn5kjllf80000gn/T//Rtmp7WHzWS/downloaded_packages

---
# Utility Work: Load Data & Investigate The Dataset Charavcteristics

In [12]:
# Input File Names:
candidateFilePath = "./data/GE2016-candidate-details.csv"
constituencyFilePath = "./data/GE2016constituencydetails.csv"
electionCountFilePath = "./data/GE2016-count-details.csv"

In [37]:
#Candidate Data Set CSV into canddf - candidate dataframe
canddf <- read.csv(candidateFilePath, sep = ",", fileEncoding="latin1")
head(canddf)

#Check for NA Values - None Returned
which(is.na(canddf))

  Constituency    Surname  First.Name      Gender Party
1 Galway West      Ó Cuív  Éamon           M      Fianna Fáil
2 Louth           Adams    Gerry           M      Sinn Féin
3 Cork  East      Ahern    Barbara         F      Fianna Fáil
4 Waterford       Ahmed    Sheik Mohiuddin M      Non-Party
5 Dublin Mid-West Akpoveta Patrick         M      Non-Party
6 Tipperary       Ambrose  Siobhán         F      Fianna Fáil
  Party.Abbreviation Count.Number Required.To.Reach.Quota
1 F.F.               14              0
2 S.F.               11              0
3 F.F.               10           3781
4 NON-P.              9              0
5 NON-P.             12              0
6 F.F.                7              0
  Required.To.Save.Deposit Votes Result   Candidate.Id Constituency.Number
1    0                      9539 Elected  165           23
2    0                     10661 Elected  160           31
3    0                      4594          169            4
4 2443                       140 Excluded 160           38
5 1813                       288 Excluded 187          643
6    0                      4472 Excluded 160           36
  Constituency.Ainm
1 Gaillimh Thiar
2 Lú
3 Corcaigh Thoir
4 Port  Lairge
5 Baile Átha Cliath Thiar-Meán
6 Tiobraid Árann

---
# Part One - Candidate Data Observation

In [100]:
# 1-a) SQL Query Style Execution: Get First&Surnames of Candidates in The Wexford Constituency 👍
wexfordCandidates = sqldf('Select Constituency, Surname,"First.Name" from canddf where Constituency = "Wexford"')
wexfordCandidates

   Constituency Surname First.Name
1  Wexford      Browne  James
2  Wexford      Byrne   Aoife
3  Wexford      Byrne   Malcolm
4  Wexford      Carthy  Ger
5  Wexford      D'arcy  Michael
6  Wexford      Dwyer   John
7  Wexford      Foxe    Caroline
8  Wexford      Hogan   Julie
9  Wexford      Howlin  Brendan
10 Wexford      Kehoe   Paul
11 Wexford      Kelly   Leonard
12 Wexford      Lloyd   David
13 Wexford      Maloney David
14 Wexford      Mythen  John
15 Wexford      Wadding Deirdre
16 Wexford      Wallace Mick
17 Wexford      Walsh   Ann

integer(0)

In [75]:
# 1-b) Get The Number of Candidates for the Laois Constituency: 👍
countLaoisCandidates = sqldf('Select COUNT(*) from canddf where Constituency = "Laois"')
cat("The Laois Constituency Had:", countLaoisCandidates[1,1], "Candidates in the 2016 General Election.")

The Laois Constituency Had: 6 Candidates in the 2016 General Election.

In [94]:
# 1-c) Get Total Number of Constituencies
countConstituenciesA = sqldf('Select DISTINCT Constituency from canddf ORDER BY Constituency ASC')
cat("In the 2016 General Election there were", nrow(countConstituenciesA), "Constituencies - canddf")
countConstituenciesA

In the 2016 General Election there were 40 Constituencies - canddf

   Constituency
1  Carlow-Kilkenny
2  Cavan-Monaghan
3  Clare
4  Cork  East
5  Cork North-Central
6  Cork North-West
7  Cork South-Central
8  Cork South-West
9  Donegal
10 Dublin Bay North
11 Dublin Bay South
12 Dublin Central
13 Dublin Fingal
14 Dublin Mid-West
15 Dublin North-West
16 Dublin Rathdown
17 Dublin South-Central
18 Dublin South-West
19 Dublin West
20 Dún Laoghaire
21 Galway East
22 Galway West
23 Kerry
24 Kildare North
25 Kildare South
26 Laois
27 Limerick City
28 Limerick County
29 Longford-Westmeath
30 Louth
31 Mayo
32 Meath East
33 Meath West
34 Offaly
35 Roscommon-Galway
36 Sligo-Leitrim
37 Tipperary
38 Waterford
39 Wexford
40 Wicklow

---
# Part Two - Constituency Data Observation

In [101]:
#Constituency Data Set CSV into constdf - constituency dataframe
constdf <- read.csv(constituencyFilePath, sep = ",", fileEncoding="latin1")
head(constdf)

#Check for NA Values - None Returned
which(is.na(canddf))

  Constituency.Name  Constituency.Ainm          Count.Number Date.Of.Election
1 Carlow Kilkenny    Ceatharlach-Cill Chainnigh 11           26/02/2016
2 Cavan Monaghan     An Cabhán-Muineachán       10           26/02/2016
3 Clare              An Clár                    12           26/02/2016
4 Cork East          Corcaigh Thoir             10           26/02/2016
5 Cork North Central Corcaigh Thuaidh-Lár       11           26/02/2016
6 Cork North West    Corcaigh Thiar Thuaidh      9           26/02/2016
  Number.Of.Candidates Number.of.Seats Quota Required.Save.Deposit Seats.Filled
1 15                   5               11669 2918                  5
2 15                   4               11931 2983                  4
3 16                   4               11401 2851                  4
4 15                   4               10562 2641                  4
5 14                   4               10235 2559                  4
6 13                   3               11740 2936                  3
  Seats.in.Constituency Spoiled Total.Electorate Total.Poll Valid.Poll
1 5                     505     107023           70514      70009
2 4                     598      90618           60248      59650
3 4                     407      83660           57407      57000
4 4                     445      83236           53251      52806
5 4                     516      81609           51690      51174
6 3                     395      67589           47353      46958
  Constituency.Number
1 1
2 2
3 3
4 4
5 5
6 6

integer(0)

In [95]:
# Get the number of constituencies in this dataset -> constituency dataset
countConstituenciesB = sqldf('Select DISTINCT "Constituency.Name" from constdf ORDER BY "Constituency.Name" ASC')
countConstituenciesB
cat("In the 2016 General Election there were", nrow(countConstituenciesB), "Constituencies - constdf")

   Constituency.Name
1  Carlow Kilkenny
2  Cavan Monaghan
3  Clare
4  Cork East
5  Cork North Central
6  Cork North West
7  Cork South Central
8  Cork South West
9  Donegal
10 Dublin Bay North
11 Dublin Bay South
12 Dublin Central
13 Dublin Fingal
14 Dublin Mid West
15 Dublin North West
16 Dublin Rathdown
17 Dublin South Central
18 Dublin South West
19 Dublin West
20 Dún Laoghaire
21 Galway East
22 Galway West
23 Kerry
24 Kildare North
25 Kildare South
26 Laois
27 Limerick City
28 Limerick County
29 Longford Westmeath
30 Louth
31 Mayo
32 Meath East
33 Meath West
34 Offaly
35 Roscommon Galway
36 Sligo Leitrim
37 Tipperary
38 Waterford
39 Wexford
40 Wicklow

In the 2016 General Election there were 40 Constituencies - constdf

In [96]:
dfCompareConstituency$CandidateSource <- countConstituenciesA

ERROR: Error in dfCompareConstituency$CandidateSource <- countConstituenciesA: object 'dfCompareConstituency' not found

In [9]:
#Count Data Set CSV into countdf - election count dataframe
countdf <- read.csv(electionCountFilePath, sep = ",", fileEncoding="latin1")
head(countdf)

  Constituency.Name Candidate.surname Candidate.First.Name Result  Count.Number
1 Louth             Adams             Gerry                        1
2 Louth             Adams             Gerry                        2
3 Louth             Adams             Gerry                        3
4 Louth             Adams             Gerry                        4
5 Louth             Adams             Gerry                        5
6 Louth             Adams             Gerry                Elected 7
  Non_Transferable Occurred.On.Count Required.To.Reach.Quota
1 0                0                 594
2 0                0                 481
3 0                0                 429
4 0                0                 347
5 0                0                 159
6 0                6                   0
  Required.To.Save.Deposit Transfers Votes Total.Votes Constituency.Number
1 0                          0       10661 10661       31
2 0                        113       10661 10774       31
3 0                         52       10661 10826       31
4 0                         82       10661 10908       31
5 0                        188       10661 11096       31
6 0                          0       10661 11278       31
  Candidate.Id
1 160
2 160
3 160
4 160
5 160
6 160